name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.4
      
      - name: Install dependencies
        working-directory: backend  
        run: go get .
      
      - name: Build
        working-directory: backend  
        run: go build -v ./...

